name: PDF

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Convert
        uses: docker://ghcr.io/willfantom/md2pdf-action:2
        with:
          md_file: README.md
          pdf_file: README.pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: README
          path: README.pdf
