name: PDF

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Convert
        uses: docker://ghcr.io/willfantom/md2pdf-action:2
        with:
          baseDir: "."
          convertedFiles: README
          cssFilePattern: "**.css"
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: README
          path: README.pdf

          # docker run --rm -v ${PWD}:/data ghcr.io/willfantom/md2pdf-action:2 --baseDir /data --convertedFiles README
