name: Notifications

on:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Send message
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, world!"}' ${{ secrets.SLACK_WEBHOOK }}
