name: Build pdf and publish it on GitHub releases

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [de, en, fr, pl, es, da]
    steps:
      - name: Step 1 - Checkout sources
        uses: actions/checkout@v4
      - name: Step 2 - Read dotenv vars
        uses: xom9ikk/dotenv@v2
      - name: Step 3.1 - Generate the documents using Docker for ${{ matrix.language }}
        run: |
          ./Scripts/build.sh ${{ matrix.language }}
      - name: Step 3.2 - Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Step 4 - Upload PDF artifact for ${{ matrix.language }}
        uses: actions/upload-artifact@v3
        with:
          name: thebox-pdf-${{ matrix.language }}
          path: Temp/Results/${{ env.THEBOX_FILENAME }}.${{ matrix.language }}.pdf
          if-no-files-found: error
          retention-days: 12

  release:
    name: release ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Step 1.1 - Checkout sources
        uses: actions/checkout@v2
      - name: Step 1.2 - Read dotenv vars
        uses: xom9ikk/dotenv@v2
      - name: Step 3. - Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            #### Changes in this Release

            - ${{ github.event.head_commit.message }}

            ##### Download files

            [![TheBox DE](https://img.shields.io/badge/DE-TheBox-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.THEBOX_FILENAME }}.pdf) 
            [![TheBox EN](https://img.shields.io/badge/EN-theBox-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.THEBOX_FILENAME }}.en.pdf)
            [![TheBox FR](https://img.shields.io/badge/FR-TheBox-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.THEBOX_FILENAME }}.fr.pdf)
            [![TheBox PL](https://img.shields.io/badge/PL-TheBox-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.THEBOX_FILENAME }}.pl.pdf)
            [![TheBox ES](https://img.shields.io/badge/ES-TheBox-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.THEBOX_FILENAME }}.es.pdf)
            [![TheBox DA](https://img.shields.io/badge/DA-TheBox-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.THEBOX_FILENAME }}.da.pdf)
            https://github.com/NULLzuEINS/thebox-docs/releases/download/1.0.40/thebox-en.pdf
          draft: false
          prerelease: false
      - name: Save upload URL for later use
        run: |
          mkdir -p Assets
          echo "${{ steps.create_release.outputs.upload_url }}" > ./Assets/upload-url.txt
      - name: Upload upload_url.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: upload-url
          path: ./Assets/upload-url.txt

  upload:
    name: upload to release ${{ github.ref_name }}
    strategy:
        matrix:
          language: [de, en, fr, pl, es, da]  
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Step 1.1 - Checkout sources
        uses: actions/checkout@v2
      - name: Step 1.2 - Read dotenv vars
        uses: xom9ikk/dotenv@v2
      - name: Step 2.1 - Download pdf artifact for ${{ matrix.language }}
        uses: actions/download-artifact@v2
        with:
          name: thebox-pdf-${{ matrix.language }}
          path: Assets/
      - name: Step 2.2 - Download upload url artifact
        uses: actions/download-artifact@v2
        with:
          name: upload-url
          path: Assets/
      - name: Step 3. - Set upload url
        run: |
          echo "UPLOAD_URL=$(cat Assets/upload-url.txt)" >> $GITHUB_ENV
          ls -lisah
      - name: Step 4. - Upload PDF for ${{ matrix.language }} as release asset
        id: upload-release-asset-pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_content_type: application/pdf
          asset_name: ${{ env.THEBOX_FILENAME }}-${{ matrix.language }}.pdf
          asset_path: ./Assets/${{ env.THEBOX_FILENAME }}.${{ matrix.language }}.pdf
