name: Build pdf and publish it on GitHub releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout sources
        uses: actions/checkout@v4
      - name: Step 2 - Read dotenv vars
        uses: xom9ikk/dotenv@v2
      - name: Step 3 - Create temporary folders
        run: |
          mkdir -p Results
          mkdir -p Temp
      - name: Step 3 - Generate the documents using Docker
        run: |
          ./Scripts/build.sh
          ls -lisah Results

      - name: Step 4.1 - Upload the single PDF Introduction artifact
        uses: actions/upload-artifact@v3
        with:
          name: thebox-pdf-introduction
          path: Results/${{ env.THEBOX_FILENAME }}.pdf
          if-no-files-found: error
          retention-days: 12

      - name: Step 5.1 - Upload the PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: thebox-pdf
          path: Results/thebox-${{ env.THEBOX_FILENAME }}.pdf
          if-no-files-found: error
          retention-days: 12

  release:
    name: release – ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Step 1.1 - Checkout sources
        uses: actions/checkout@v2
      - name: Step 1.2 - Read dotenv vars
        uses: xom9ikk/dotenv@v2

      - name: Step 2.1 Download pdf artifact
        uses: actions/download-artifact@v2
        with:
          name: thebox-pdf
          path: thebox-pdf
      - name: Step 3. Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            #### Changes in this Release

            - ${{ github.event.head_commit.message }}

            ##### Download single files

            | Language     | Download |
            | ------------ | -------- |
            | DE | [![Badge CV](https://img.shields.io/badge/DE-TheBox-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.THEBOX_FILENAME }}.pdf) | 
            | EN | [![Badge CV](https://img.shields.io/badge/EN-theBox-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ env.THEBOX_FILENAME }}.en.pdf) | 

          draft: false
          prerelease: false

      - name: Step 4.1 Upload PDF as Release Asset
        id: upload-release-asset-pdf-introduction
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.THEBOX_FILENAME }}/${{ env.THEBOX_FILENAME }}.pdf
          asset_name: ${{ env.THEBOX_FILENAME }}.pdf
          asset_content_type: application/pdf

