name: Translate README

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language-code: ['zh-CN', 'cs', 'da', 'nl', 'el', 'es', 'fr', 'de', 'hu', 'it', 'ja']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Adding README - ${{ matrix.language-code }}
        uses: dephraiim/translate-readme@main
        with:
          LANG: ${{ matrix.language-code }}
