name: Translate README

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
      - name: Adding README - Czech
        uses: dephraiim/translate-readme@main
        with:
          LANG: cs
      - name: Adding README - Danish
        uses: dephraiim/translate-readme@main
        with:
          LANG: da
      - name: Adding README - Dutch
        uses: dephraiim/translate-readme@main
        with:
          LANG: nl
      - name: Adding README - Greek
        uses: dephraiim/translate-readme@main
        with:
          LANG: el
      - name: Adding README - Spanish
        uses: dephraiim/translate-readme@main
        with:
          LANG: es
      - name: Adding README - Estonian
        uses: dephraiim/translate-readme@main
        with:
          LANG: et
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
            LANG: en
      - name: Adding README - Finnish
        uses: dephraiim/translate-readme@main
        with:
          LANG: fi
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
      - name: Adding README - Hindi
        uses: dephraiim/translate-readme@main
        with:
          LANG: hi
      - name: Adding README - Italien
        uses: dephraiim/translate-readme@main
        with:
          LANG: it
      - name: Adding README - Japanese
        uses: dephraiim/translate-readme@main
        with:
          LANG: ja
      - name: Adding README - Korean
        uses: dephraiim/translate-readme@main
        with:
          LANG: ko
      - name: Adding README - Norwegian
        uses: dephraiim/translate-readme@main
        with:
          LANG: no
      - name: Adding README - Polski
        uses: dephraiim/translate-readme@main
        with:
          LANG: pl
      - name: Adding README - Portuguese
        uses: dephraiim/translate-readme@main
        with:
          LANG: pt
      - name: Adding README - Romanian
        uses: dephraiim/translate-readme@main
        with:
          LANG: ro
      - name: Adding README - Russian
        uses: dephraiim/translate-readme@main
        with:
          LANG: ru
      - name: Adding README - Swedish
        uses: dephraiim/translate-readme@main
        with:
          LANG: sv
      - name: Adding README - Serbo-Croatian
        uses: dephraiim/translate-readme@main
        with:
          LANG: sr
      - name: Adding README - Turkish
        uses: dephraiim/translate-readme@main
        with:
          LANG: tr
      - name: Adding README - Ukrainian
        uses: dephraiim/translate-readme@main
        with:
          LANG: uk
      - name: Adding README - Urdu
        uses: dephraiim/translate-readme@main
        with:
          LANG: ur
      - name: Adding README - Vietnamese
        uses: dephraiim/translate-readme@main
        with:
          LANG: vi

  trigger_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger release workflow

        run: |
            curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/pdf.yml/dispatches" \
            -d '{"ref":"main"}'
